// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALd6MsulM91M5xJ-XZC8iccZDFzSXz-yE',
    appId: '1:1026336901012:web:a63d2eb945eee2a8927181',
    messagingSenderId: '1026336901012',
    projectId: 'lifelinker-7ffb8',
    authDomain: 'lifelinker-7ffb8.firebaseapp.com',
    storageBucket: 'lifelinker-7ffb8.firebasestorage.app',
    measurementId: 'G-SKTJZZYRET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9FSuS-frS3fjEk0ySmRDvyVXrPTMLxw',
    appId: '1:1026336901012:android:67f405efc5e86c08927181',
    messagingSenderId: '1026336901012',
    projectId: 'lifelinker-7ffb8',
    storageBucket: 'lifelinker-7ffb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUc8xafMccbPRncrYKH3vFEbLVuHPJI38',
    appId: '1:1026336901012:ios:04befee5f38fa434927181',
    messagingSenderId: '1026336901012',
    projectId: 'lifelinker-7ffb8',
    storageBucket: 'lifelinker-7ffb8.firebasestorage.app',
    iosBundleId: 'com.example.lifelinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUc8xafMccbPRncrYKH3vFEbLVuHPJI38',
    appId: '1:1026336901012:ios:04befee5f38fa434927181',
    messagingSenderId: '1026336901012',
    projectId: 'lifelinker-7ffb8',
    storageBucket: 'lifelinker-7ffb8.firebasestorage.app',
    iosBundleId: 'com.example.lifelinker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALd6MsulM91M5xJ-XZC8iccZDFzSXz-yE',
    appId: '1:1026336901012:web:26199022ae013b1d927181',
    messagingSenderId: '1026336901012',
    projectId: 'lifelinker-7ffb8',
    authDomain: 'lifelinker-7ffb8.firebaseapp.com',
    storageBucket: 'lifelinker-7ffb8.firebasestorage.app',
    measurementId: 'G-DEB1VFEBQM',
  );
}
